main:
    log_file: /opt/garnet/log/garnet.log
    log_level: info
    agent_cache_directory: /opt/garnet/cache
    language: en
    interval: 300
    agent_subprocesses: 10
    bind_port: 4000
    api_server_name: 10.32.6.6
    api_server_port: 6000
    api_server_https: False
    api_server_uri: /infoset/api/v1

agents:
    - agent_name: _garnet
      agent_enabled: True
      agent_filename: bin/agents/_garnet.py
      monitor_agent_pid: True

    - agent_name: linux
      agent_enabled: True
      agent_filename: bin/agents/linux.py
      agent_port: 5001
      monitor_agent_pid: True
      agent_devicenames:
        - 10.32.6.6

    - agent_name: remote_linux_active
      agent_enabled: True
      agent_filename: bin/agents/remote_linux_active.py

    - agent_name: remote_linux_passive
      agent_enabled: True
      agent_filename: bin/agents/remote_linux_passive.py
